//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JianzhouWS.JianzhouWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.nineorange.com", ConfigurationName="JianzhouWebservice.BusinessService")]
    public interface BusinessService {
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.getReceivedMsgResponse getReceivedMsg(JianzhouWS.JianzhouWebservice.getReceivedMsg request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.sendPersonalMessagesResponse sendPersonalMessages(JianzhouWS.JianzhouWebservice.sendPersonalMessages request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.modifyPasswordResponse modifyPassword(JianzhouWS.JianzhouWebservice.modifyPassword request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.getReceiptResponse getReceipt(JianzhouWS.JianzhouWebservice.getReceipt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.sendBatchMessageResponse sendBatchMessage(JianzhouWS.JianzhouWebservice.sendBatchMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.validateUserResponse validateUser(JianzhouWS.JianzhouWebservice.validateUser request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.sendMessageResponse sendMessage(JianzhouWS.JianzhouWebservice.sendMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.sendTimelyMessageResponse sendTimelyMessage(JianzhouWS.JianzhouWebservice.sendTimelyMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.sendMmsMessagesResponse sendMmsMessages(JianzhouWS.JianzhouWebservice.sendMmsMessages request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JianzhouWS.JianzhouWebservice.getUserInfoResponse getUserInfo(JianzhouWS.JianzhouWebservice.getUserInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceivedMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceivedMsg", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.getReceivedMsgBody Body;
        
        public getReceivedMsg() {
        }
        
        public getReceivedMsg(JianzhouWS.JianzhouWebservice.getReceivedMsgBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceivedMsgBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int param;
        
        public getReceivedMsgBody() {
        }
        
        public getReceivedMsgBody(string account, string password, int param) {
            this.account = account;
            this.password = password;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceivedMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceivedMsgResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.getReceivedMsgResponseBody Body;
        
        public getReceivedMsgResponse() {
        }
        
        public getReceivedMsgResponse(JianzhouWS.JianzhouWebservice.getReceivedMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceivedMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReceivedMsgReturn;
        
        public getReceivedMsgResponseBody() {
        }
        
        public getReceivedMsgResponseBody(string getReceivedMsgReturn) {
            this.getReceivedMsgReturn = getReceivedMsgReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendPersonalMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendPersonalMessages", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendPersonalMessagesBody Body;
        
        public sendPersonalMessages() {
        }
        
        public sendPersonalMessages(JianzhouWS.JianzhouWebservice.sendPersonalMessagesBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendPersonalMessagesBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destMobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgContents;
        
        public sendPersonalMessagesBody() {
        }
        
        public sendPersonalMessagesBody(string account, string password, string destMobiles, string msgContents) {
            this.account = account;
            this.password = password;
            this.destMobiles = destMobiles;
            this.msgContents = msgContents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendPersonalMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendPersonalMessagesResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendPersonalMessagesResponseBody Body;
        
        public sendPersonalMessagesResponse() {
        }
        
        public sendPersonalMessagesResponse(JianzhouWS.JianzhouWebservice.sendPersonalMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendPersonalMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendPersonalMessagesReturn;
        
        public sendPersonalMessagesResponseBody() {
        }
        
        public sendPersonalMessagesResponseBody(int sendPersonalMessagesReturn) {
            this.sendPersonalMessagesReturn = sendPersonalMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyPassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyPassword", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.modifyPasswordBody Body;
        
        public modifyPassword() {
        }
        
        public modifyPassword(JianzhouWS.JianzhouWebservice.modifyPasswordBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class modifyPasswordBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public modifyPasswordBody() {
        }
        
        public modifyPasswordBody(string account, string oldPassword, string newPassword) {
            this.account = account;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyPasswordResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.modifyPasswordResponseBody Body;
        
        public modifyPasswordResponse() {
        }
        
        public modifyPasswordResponse(JianzhouWS.JianzhouWebservice.modifyPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class modifyPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int modifyPasswordReturn;
        
        public modifyPasswordResponseBody() {
        }
        
        public modifyPasswordResponseBody(int modifyPasswordReturn) {
            this.modifyPasswordReturn = modifyPasswordReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceipt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceipt", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.getReceiptBody Body;
        
        public getReceipt() {
        }
        
        public getReceipt(JianzhouWS.JianzhouWebservice.getReceiptBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceiptBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int taskID;
        
        public getReceiptBody() {
        }
        
        public getReceiptBody(string account, string password, int taskID) {
            this.account = account;
            this.password = password;
            this.taskID = taskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceiptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceiptResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.getReceiptResponseBody Body;
        
        public getReceiptResponse() {
        }
        
        public getReceiptResponse(JianzhouWS.JianzhouWebservice.getReceiptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceiptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReceiptReturn;
        
        public getReceiptResponseBody() {
        }
        
        public getReceiptResponseBody(string getReceiptReturn) {
            this.getReceiptReturn = getReceiptReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessage", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendBatchMessageBody Body;
        
        public sendBatchMessage() {
        }
        
        public sendBatchMessage(JianzhouWS.JianzhouWebservice.sendBatchMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgText;
        
        public sendBatchMessageBody() {
        }
        
        public sendBatchMessageBody(string account, string password, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendBatchMessageResponseBody Body;
        
        public sendBatchMessageResponse() {
        }
        
        public sendBatchMessageResponse(JianzhouWS.JianzhouWebservice.sendBatchMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendBatchMessageReturn;
        
        public sendBatchMessageResponseBody() {
        }
        
        public sendBatchMessageResponseBody(int sendBatchMessageReturn) {
            this.sendBatchMessageReturn = sendBatchMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUser", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.validateUserBody Body;
        
        public validateUser() {
        }
        
        public validateUser(JianzhouWS.JianzhouWebservice.validateUserBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class validateUserBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public validateUserBody() {
        }
        
        public validateUserBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.validateUserResponseBody Body;
        
        public validateUserResponse() {
        }
        
        public validateUserResponse(JianzhouWS.JianzhouWebservice.validateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class validateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int validateUserReturn;
        
        public validateUserResponseBody() {
        }
        
        public validateUserResponseBody(int validateUserReturn) {
            this.validateUserReturn = validateUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendMessageBody Body;
        
        public sendMessage() {
        }
        
        public sendMessage(JianzhouWS.JianzhouWebservice.sendMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgText;
        
        public sendMessageBody() {
        }
        
        public sendMessageBody(string account, string password, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendMessageResponseBody Body;
        
        public sendMessageResponse() {
        }
        
        public sendMessageResponse(JianzhouWS.JianzhouWebservice.sendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendMessageReturn;
        
        public sendMessageResponseBody() {
        }
        
        public sendMessageResponseBody(int sendMessageReturn) {
            this.sendMessageReturn = sendMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTimelyMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTimelyMessage", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendTimelyMessageBody Body;
        
        public sendTimelyMessage() {
        }
        
        public sendTimelyMessage(JianzhouWS.JianzhouWebservice.sendTimelyMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendTimelyMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        public sendTimelyMessageBody() {
        }
        
        public sendTimelyMessageBody(string account, string password, string sendDateTime, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTimelyMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTimelyMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendTimelyMessageResponseBody Body;
        
        public sendTimelyMessageResponse() {
        }
        
        public sendTimelyMessageResponse(JianzhouWS.JianzhouWebservice.sendTimelyMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendTimelyMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendTimelyMessageReturn;
        
        public sendTimelyMessageResponseBody() {
        }
        
        public sendTimelyMessageResponseBody(int sendTimelyMessageReturn) {
            this.sendTimelyMessageReturn = sendTimelyMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMmsMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMmsMessages", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendMmsMessagesBody Body;
        
        public sendMmsMessages() {
        }
        
        public sendMmsMessages(JianzhouWS.JianzhouWebservice.sendMmsMessagesBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMmsMessagesBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mmsString;
        
        public sendMmsMessagesBody() {
        }
        
        public sendMmsMessagesBody(string account, string password, string phones, string mmsString) {
            this.account = account;
            this.password = password;
            this.phones = phones;
            this.mmsString = mmsString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMmsMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMmsMessagesResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.sendMmsMessagesResponseBody Body;
        
        public sendMmsMessagesResponse() {
        }
        
        public sendMmsMessagesResponse(JianzhouWS.JianzhouWebservice.sendMmsMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMmsMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendMmsMessagesReturn;
        
        public sendMmsMessagesResponseBody() {
        }
        
        public sendMmsMessagesResponseBody(int sendMmsMessagesReturn) {
            this.sendMmsMessagesReturn = sendMmsMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfo", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.getUserInfoBody Body;
        
        public getUserInfo() {
        }
        
        public getUserInfo(JianzhouWS.JianzhouWebservice.getUserInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getUserInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getUserInfoBody() {
        }
        
        public getUserInfoBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfoResponse", Namespace="http://service.nineorange.com", Order=0)]
        public JianzhouWS.JianzhouWebservice.getUserInfoResponseBody Body;
        
        public getUserInfoResponse() {
        }
        
        public getUserInfoResponse(JianzhouWS.JianzhouWebservice.getUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserInfoReturn;
        
        public getUserInfoResponseBody() {
        }
        
        public getUserInfoResponseBody(string getUserInfoReturn) {
            this.getUserInfoReturn = getUserInfoReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusinessServiceChannel : JianzhouWS.JianzhouWebservice.BusinessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessServiceClient : System.ServiceModel.ClientBase<JianzhouWS.JianzhouWebservice.BusinessService>, JianzhouWS.JianzhouWebservice.BusinessService {
        
        public BusinessServiceClient() {
        }
        
        public BusinessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.getReceivedMsgResponse JianzhouWS.JianzhouWebservice.BusinessService.getReceivedMsg(JianzhouWS.JianzhouWebservice.getReceivedMsg request) {
            return base.Channel.getReceivedMsg(request);
        }
        
        public string getReceivedMsg(string account, string password, int param) {
            JianzhouWS.JianzhouWebservice.getReceivedMsg inValue = new JianzhouWS.JianzhouWebservice.getReceivedMsg();
            inValue.Body = new JianzhouWS.JianzhouWebservice.getReceivedMsgBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.param = param;
            JianzhouWS.JianzhouWebservice.getReceivedMsgResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).getReceivedMsg(inValue);
            return retVal.Body.getReceivedMsgReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.sendPersonalMessagesResponse JianzhouWS.JianzhouWebservice.BusinessService.sendPersonalMessages(JianzhouWS.JianzhouWebservice.sendPersonalMessages request) {
            return base.Channel.sendPersonalMessages(request);
        }
        
        public int sendPersonalMessages(string account, string password, string destMobiles, string msgContents) {
            JianzhouWS.JianzhouWebservice.sendPersonalMessages inValue = new JianzhouWS.JianzhouWebservice.sendPersonalMessages();
            inValue.Body = new JianzhouWS.JianzhouWebservice.sendPersonalMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destMobiles = destMobiles;
            inValue.Body.msgContents = msgContents;
            JianzhouWS.JianzhouWebservice.sendPersonalMessagesResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).sendPersonalMessages(inValue);
            return retVal.Body.sendPersonalMessagesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.modifyPasswordResponse JianzhouWS.JianzhouWebservice.BusinessService.modifyPassword(JianzhouWS.JianzhouWebservice.modifyPassword request) {
            return base.Channel.modifyPassword(request);
        }
        
        public int modifyPassword(string account, string oldPassword, string newPassword) {
            JianzhouWS.JianzhouWebservice.modifyPassword inValue = new JianzhouWS.JianzhouWebservice.modifyPassword();
            inValue.Body = new JianzhouWS.JianzhouWebservice.modifyPasswordBody();
            inValue.Body.account = account;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            JianzhouWS.JianzhouWebservice.modifyPasswordResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).modifyPassword(inValue);
            return retVal.Body.modifyPasswordReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.getReceiptResponse JianzhouWS.JianzhouWebservice.BusinessService.getReceipt(JianzhouWS.JianzhouWebservice.getReceipt request) {
            return base.Channel.getReceipt(request);
        }
        
        public string getReceipt(string account, string password, int taskID) {
            JianzhouWS.JianzhouWebservice.getReceipt inValue = new JianzhouWS.JianzhouWebservice.getReceipt();
            inValue.Body = new JianzhouWS.JianzhouWebservice.getReceiptBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.taskID = taskID;
            JianzhouWS.JianzhouWebservice.getReceiptResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).getReceipt(inValue);
            return retVal.Body.getReceiptReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.sendBatchMessageResponse JianzhouWS.JianzhouWebservice.BusinessService.sendBatchMessage(JianzhouWS.JianzhouWebservice.sendBatchMessage request) {
            return base.Channel.sendBatchMessage(request);
        }
        
        public int sendBatchMessage(string account, string password, string destmobile, string msgText) {
            JianzhouWS.JianzhouWebservice.sendBatchMessage inValue = new JianzhouWS.JianzhouWebservice.sendBatchMessage();
            inValue.Body = new JianzhouWS.JianzhouWebservice.sendBatchMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            JianzhouWS.JianzhouWebservice.sendBatchMessageResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).sendBatchMessage(inValue);
            return retVal.Body.sendBatchMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.validateUserResponse JianzhouWS.JianzhouWebservice.BusinessService.validateUser(JianzhouWS.JianzhouWebservice.validateUser request) {
            return base.Channel.validateUser(request);
        }
        
        public int validateUser(string account, string password) {
            JianzhouWS.JianzhouWebservice.validateUser inValue = new JianzhouWS.JianzhouWebservice.validateUser();
            inValue.Body = new JianzhouWS.JianzhouWebservice.validateUserBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            JianzhouWS.JianzhouWebservice.validateUserResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).validateUser(inValue);
            return retVal.Body.validateUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.sendMessageResponse JianzhouWS.JianzhouWebservice.BusinessService.sendMessage(JianzhouWS.JianzhouWebservice.sendMessage request) {
            return base.Channel.sendMessage(request);
        }
        
        public int sendMessage(string account, string password, string destmobile, string msgText) {
            JianzhouWS.JianzhouWebservice.sendMessage inValue = new JianzhouWS.JianzhouWebservice.sendMessage();
            inValue.Body = new JianzhouWS.JianzhouWebservice.sendMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            JianzhouWS.JianzhouWebservice.sendMessageResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).sendMessage(inValue);
            return retVal.Body.sendMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.sendTimelyMessageResponse JianzhouWS.JianzhouWebservice.BusinessService.sendTimelyMessage(JianzhouWS.JianzhouWebservice.sendTimelyMessage request) {
            return base.Channel.sendTimelyMessage(request);
        }
        
        public int sendTimelyMessage(string account, string password, string sendDateTime, string destmobile, string msgText) {
            JianzhouWS.JianzhouWebservice.sendTimelyMessage inValue = new JianzhouWS.JianzhouWebservice.sendTimelyMessage();
            inValue.Body = new JianzhouWS.JianzhouWebservice.sendTimelyMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            JianzhouWS.JianzhouWebservice.sendTimelyMessageResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).sendTimelyMessage(inValue);
            return retVal.Body.sendTimelyMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.sendMmsMessagesResponse JianzhouWS.JianzhouWebservice.BusinessService.sendMmsMessages(JianzhouWS.JianzhouWebservice.sendMmsMessages request) {
            return base.Channel.sendMmsMessages(request);
        }
        
        public int sendMmsMessages(string account, string password, string phones, string mmsString) {
            JianzhouWS.JianzhouWebservice.sendMmsMessages inValue = new JianzhouWS.JianzhouWebservice.sendMmsMessages();
            inValue.Body = new JianzhouWS.JianzhouWebservice.sendMmsMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.phones = phones;
            inValue.Body.mmsString = mmsString;
            JianzhouWS.JianzhouWebservice.sendMmsMessagesResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).sendMmsMessages(inValue);
            return retVal.Body.sendMmsMessagesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JianzhouWS.JianzhouWebservice.getUserInfoResponse JianzhouWS.JianzhouWebservice.BusinessService.getUserInfo(JianzhouWS.JianzhouWebservice.getUserInfo request) {
            return base.Channel.getUserInfo(request);
        }
        
        public string getUserInfo(string account, string password) {
            JianzhouWS.JianzhouWebservice.getUserInfo inValue = new JianzhouWS.JianzhouWebservice.getUserInfo();
            inValue.Body = new JianzhouWS.JianzhouWebservice.getUserInfoBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            JianzhouWS.JianzhouWebservice.getUserInfoResponse retVal = ((JianzhouWS.JianzhouWebservice.BusinessService)(this)).getUserInfo(inValue);
            return retVal.Body.getUserInfoReturn;
        }
    }
}
